# Generated by Django 3.1 on 2020-08-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question_link',
        ),
        migrations.RemoveField(
            model_name='option',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='form_link',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RemoveField(
            model_name='type',
            name='user',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
