# Generated by Django 3.1 on 2020-08-16 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='user',
        ),
        migrations.RemoveField(
            model_name='option',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AddField(
            model_name='form',
            name='form_link',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
